"""update project member relationsip

Revision ID: 112ca68637af
Revises: d7d5ccb4ebd7
Create Date: 2026-06-29 01:03:22.955610

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "112ca68637af"
down_revision: Union[str, Sequence[str], None] = "d7d5ccb4ebd7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM project_member WHERE project_id IS NULL")
    op.drop_constraint(
        op.f("project_members_project_id_fkey"), "project_members", type_="foreignkey"
    )
    op.create_foreign_key(
        "project_members_project_id_fkey",
        "project_members",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_project_member_project_id", "project_members", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("project_members_project_id_fkey"),
        "project_members",
        "projects",
        ["project_id"],
        ["id"],
    )
    # ### end Alembic commands ###
