"""change check constraint value in board columns

Revision ID: 39fe45e40f4c
Revises: 9ee161cffbc4
Create Date: 2026-06-19 12:43:47.280284

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39fe45e40f4c"
down_revision: Union[str, Sequence[str], None] = "9ee161cffbc4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_status_group", "board_columns")
    op.create_check_constraint(
        "check_status_group",
        "board_columns",
        "status_group IN ('pending', 'in_progress', 'done', 'cancelled')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_status_group", "board_columns")
    op.create_check_constraint(
        "check_status_group",
        "board_columns",
        "status_group IN ('todo', 'in_progress', 'done','cancelled')",
    )
    # ### end Alembic commands ###
