"""add timestamps to members roles table

Revision ID: 4bba4f67afe5
Revises: 67a92a60abea
Create Date: 2026-06-24 00:53:59.758683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bba4f67afe5'
down_revision: Union[str, Sequence[str], None] = '67a92a60abea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_roles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('member_roles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_roles', 'updated_at')
    op.drop_column('member_roles', 'created_at')
    # ### end Alembic commands ###
