"""rename owner_id to creator_id in tasks table

Revision ID: 4dcfee6d3e91
Revises: 7c6757390175
Create Date: 2026-06-17 17:53:40.332411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dcfee6d3e91'
down_revision: Union[str, Sequence[str], None] = '7c6757390175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('creator_id', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_tasks_owner_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_creator_id'), 'tasks', ['creator_id'], unique=False)
    op.drop_column('tasks', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('owner_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tasks_creator_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_owner_id'), 'tasks', ['owner_id'], unique=False)
    op.drop_column('tasks', 'creator_id')
    # ### end Alembic commands ###
