"""remove all enums and owner_id

Revision ID: 7c6757390175
Revises: ca5f0c85e8ae
Create Date: 2026-06-17 17:46:34.304658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c6757390175'
down_revision: Union[str, Sequence[str], None] = 'ca5f0c85e8ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_column('projects', 'owner_id')
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='taskpriority'),
               type_=sa.String(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=sa.String(length=255),
               type_=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='taskpriority'),
               nullable=True)
    op.add_column('projects', sa.Column('owner_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    # ### end Alembic commands ###
