"""add unique constraint in project_members

Revision ID: 9ee161cffbc4
Revises: 4dcfee6d3e91
Create Date: 2026-06-19 12:41:30.585752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee161cffbc4'
down_revision: Union[str, Sequence[str], None] = '4dcfee6d3e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'project_members', ['project_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_members', type_='unique')
    # ### end Alembic commands ###
