"""change role name in check role const

Revision ID: d7d5ccb4ebd7
Revises: 1989cadd6505
Create Date: 2026-06-26 20:03:49.439076

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d7d5ccb4ebd7"
down_revision: Union[str, Sequence[str], None] = "1989cadd6505"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_role", "project_members", type_="CHECK")
    op.create_check_constraint(
        "check_role", "project_members", "role IN ('owner', 'manager', 'member')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_role", "project_members", type_="CHECK")
    op.create_check_constraint(
        "check_role", "project_members", "role IN ('owner', 'admin', 'member')"
    )
    # ### end Alembic commands ###
