from enum import StrEnum


class TaskEventType(StrEnum):
    PROJECT_CREATE = "PROJECT_CREATE"
    PROJECT_UPDATE = "PROJECT_UPDATE"
    PROJECT_DELETE = "PROJECT_DELETE"
    PROJECT_MEMBER_ADD = "PROJECT_MEMBER_ADD"
    PROJECT_MEMBER_UPDATE = "PROJECT_MEMBER_UPDATE"
    PROJECT_MEMBER_DELETE = "PROJECT_MEMBER_DELETE"
    BOARD_CREATE = "BOARD_CREATE"
    BOARD_UPDATE = "BOARD_UPDATE"
    BOARD_DELETE = "BOARD_DELETE"
    BOARD_COLUMN_CREATE = "BOARD_COLUMN_CREATE"
    BOARD_COLUMN_DELETE = "BOARD_COLUMN_DELETE"
    TASK_CREATE = "TASK_CREATE"
    TASK_UPDATE = "TASK_UPDATE"
    TASK_DELETE = "TASK_DELETE"
    TASK_ASSIGN = "TASK_ASSIGN"
    TASK_UNASSIGN = "TASK_UNASSIGN"